const Attempt = require("../models/Attempt");
const Problem = require("../models/Problem");
const User = require("../models/User");
const STANDARD_DESIGNS = require("../data/standardDesigns");
const { callForEvaluation, callForProblem } = require("../utils/aiClient");

// ─── POST /api/designs/submit
exports.submitDesign = async (req, res) => {
    try {
        const {
            problemSlug,
            problemTitle,
            isCustomProblem,
            diagramData,
            textExplanation,
            timeTaken,
            diagramImage
        } = req.body;

        if (!problemTitle?.trim())
            return res.status(400).json({ error: "Problem title is required." });
        if (!diagramData?.nodes?.length || diagramData.nodes.length < 2)
            return res.status(400).json({ error: "Please add at least 2 components to your diagram." });

        // Build human-readable diagram description for the prompt
        const nodeList = diagramData.nodes.map((n) => n.type).join(", ");
        const edgeList = diagramData.edges
            .map((e) => {
                const f = diagramData.nodes.find((n) => n.id === e.from)?.type || e.from;
                const t = diagramData.nodes.find((n) => n.id === e.to)?.type || e.to;
                return `${f} → ${t}`;
            })
            .join("; ");
        console.log(nodeList);
        console.log("Edges List");
        console.log(edgeList);


        // ─────────────────────────────────────────────────────────────────────
        // STEP 1: RESOLVE REFERENCE DESIGN
        //  TIER 1 — Check in-memory STANDARD_DESIGNS (preset problems only)
        //  TIER 2 — Check MongoDB (catches previously AI-generated custom problems)
        //  TIER 3 — AI generates the standard design + saves it to MongoDB
        //           so the NEXT user who submits the same custom problem gets it
        //           from Tier 2 for free
        // ─────────────────────────────────────────────────────────────────────
        let standardDesign = null;
        let matchInfo = null;
        let dbProblem = null;
        // ── TIER 1: In-memory preset (YouTube, Uber, WhatsApp ...)
        // for the standardf problems
        if (!isCustomProblem && problemSlug && STANDARD_DESIGNS[problemSlug]) {
            standardDesign = STANDARD_DESIGNS[problemSlug];
            matchInfo = { tier: 1, source: "preset-memory", slug: problemSlug };
            console.info(`[Design] TIER 1: "${problemTitle}" → in-memory preset standard design`);
        }
        // ── TIER 2: MongoDB lookup ─────────────────────────────────────────────
        // Covers:
        //   a) Preset problems that also exist in DB (richer data)
        //   b) Custom problems previously generated by AI and saved
        if (!standardDesign) { // if not found in static presets, check DB
            // Build the slug to look up
            const lookupSlug = problemSlug || deriveProblemSlug(problemTitle);

            dbProblem = await Problem.findOne({ slug: lookupSlug }).lean(); // check in db

            if (dbProblem?.standardDesign?.criticalComponents?.length) {
                standardDesign = dbProblem.standardDesign;
                matchInfo = { tier: 2, source: "db-cache", slug: lookupSlug };
                console.info(`[Design] TIER 2: "${problemTitle}" → found in MongoDB (slug: "${lookupSlug}")`);
            }
        }
        // ── TIER 3: AI generates reference + saves to MongoDB ─────────────────
        // After generation: saves to DB so next user gets it free from Tier 2
        if (!standardDesign) {
            const derivedSlug = problemSlug || deriveProblemSlug(problemTitle);
            console.info(`[Design] TIER 3: "${problemTitle}" → not in DB, generating reference via AI...`);
            try {
                const generatedDesign = await generateStandardDesignViaAI(problemTitle); // gen the design
                if (generatedDesign) {
                    standardDesign = generatedDesign;
                    matchInfo = { tier: 3, source: "ai-generated" };
                    // Save to MongoDB so next user gets this from Tier 2 (free)
                    try {
                        await Problem.findOneAndUpdate(
                            { slug: derivedSlug },
                            {
                                $setOnInsert: { // only insert if not exist
                                    slug: derivedSlug,
                                    title: problemTitle,
                                    description: generatedDesign.summary || "",
                                    standardDesign: generatedDesign,
                                    isCustom: true,
                                    difficulty: "Medium",
                                    estimatedTime: 45,
                                    tags: ["Custom"],
                                },
                            },
                            { upsert: true, new: true }
                        );
                        console.info(`[Design] TIER 3: Saved "${derivedSlug}" to MongoDB — next user gets it free`);
                    } catch (saveErr) {
                        // Duplicate key = race condition (two users submitted same problem simultaneously)
                        // Not a problem — both get evaluated, DB already has it or will have it
                        if (saveErr.code !== 11000) {
                            console.warn(`[Design] TIER 3: Failed to save to MongoDB:`, saveErr.message);
                        }
                    }
                }
            } catch (aiErr) {
                // AI generation failed — evaluate without a reference
                console.warn(`[Design] TIER 3: AI reference generation failed: ${aiErr.message}`);
                matchInfo = { tier: 3, source: "failed" };
            }
        }

        //  Build evaluation prompt
        const prompt = buildEvaluationPrompt({
            problemTitle,
            nodeList,
            edgeList,
            textExplanation,
            standardDesign,
            matchInfo,
        });

        //  Call AI for evaluation
        const message = await callForEvaluation({
            max_tokens: 1500,
            messages: [{ role: "user", content: prompt }],
        });

        //  Parse JSON response safely
        let evaluation;
        const rawText = message.text;
        try {
            const clean = rawText
                .replace(/```json[\s\S]*?```|```[\s\S]*?```/g,
                    (m) => m.replace(/```json?\n?/g, "").replace(/\n?```/g, ""))
                .trim();
            evaluation = JSON.parse(clean);
        } catch {
            const match = rawText.match(/\{[\s\S]+\}/);
            if (!match) {
                return res.status(500).json({
                    error: "AI returned an unexpected format. Please try submitting again.",
                });
            }
            evaluation = JSON.parse(match[0]);
        }

        // Persist attempt
        const attempt = await Attempt.create({
            user: req.user._id,
            problem: dbProblem?._id || undefined,
            problemTitle,
            isCustomProblem: !!isCustomProblem,
            diagramData,
            diagramImage,
            textExplanation: textExplanation || "",
            score: evaluation.score,
            summary: evaluation.summary,
            strengths: evaluation.strengths || [],
            improvements: evaluation.improvements || [],
            weakAreas: evaluation.weakAreas || [],
            referenceComponents: evaluation.referenceComponents || [],
            missingCriticalComponents: evaluation.missingCriticalComponents || [],
            antiPatternsFound: evaluation.antiPatternsFound || [],
            scoringBreakdown: evaluation.scoringBreakdown || {},
            comparisonWithStandard: evaluation.comparisonWithStandard || null,
            timeTaken: timeTaken || 0,
            status: "evaluated",
        });

        //  Update user stats and weak areas
        const userDoc = await User.findById(req.user._id);

        const newTotalScore = (userDoc.totalScore || 0) + evaluation.score;
        const newAttempts = (userDoc.attempts || 0) + 1;

        let updateData = {
            totalScore: newTotalScore,
            attempts: newAttempts,
            avgScore: newTotalScore / newAttempts,
        };

        if (evaluation.weakAreas?.length) {
            updateData.weakAreas = [
                ...new Set([
                    ...evaluation.weakAreas,
                    ...(userDoc.weakAreas || [])
                ])
            ].slice(0, 5);
        }

        await User.findByIdAndUpdate(req.user._id, updateData);

        res.status(201).json({
            attemptId: attempt._id,
            evaluation,
            _matchInfo: matchInfo,
            _provider: message.provider,
        });



    } catch (err) {
        console.error("submitDesign:", err);
        if (err?.status === 429) {
            return res.status(429).json({
                error: "AI service is busy. Please wait 30 seconds and try again.",
                retryAfter: 30,
            });
        }
        res.status(500).json({ error: "Evaluation failed. Please try again." });
    }
};

function deriveProblemSlug(title) {
    return (title || "")
        .toLowerCase()
        .trim()
        .replace(/^(design|build|create|make)\s+/i, "")  // strip leading verb
        .replace(/[^a-z0-9\s-]/g, "")                    // remove special chars
        .replace(/\s+/g, "-")                             // spaces → hyphens
        .replace(/-+/g, "-")                              // collapse multiple hyphens
        .slice(0, 80);                                    // max length
}
// generate the desing from the Ai -->
async function generateStandardDesignViaAI(systemName) {
    const { text } = await callForProblem({
        max_tokens: 1200,
        messages: [{
            role: "user",
            content: `You are a principal engineer at Google.
Generate the industry-standard reference architecture for: "${systemName}".

Return ONLY valid JSON (no markdown, no extra text):
{
  "summary": "<2 sentence description>",
  "components": ["<component 1>", "<up to 12 components>"],
  "expectedEdges": [
    "<ComponentA → ComponentB>",
    "<up to 12 critical connections that must exist>"
  ],
  "criticalComponents": ["<4-6 must-have components>"],
  "antiPatterns": ["<3-5 common mistakes>"],
  "scalabilityDecisions": ["<3-4 key scaling decisions>"],
  "faultToleranceMechanisms": ["<2-3 reliability mechanisms>"],
  "estimatedScale": {
    "dau": "<daily active users>",
    "requestsPerDay": "<request volume>",
    "storageNeeds": "<storage estimate>"
  }
}`,
        }],
    });

    const clean = text
        .replace(/```json[\s\S]*?```|```[\s\S]*?```/g,
            (m) => m.replace(/```json?\n?/g, "").replace(/\n?```/g, ""))
        .trim();

    try {
        return JSON.parse(clean);
    } catch {
        const match = clean.match(/\{[\s\S]+\}/);
        return match ? JSON.parse(match[0]) : null;
    }
}

// Evaluation prompt builder
function buildEvaluationPrompt({
    problemTitle,
    nodeList,
    edgeList,
    textExplanation,
    standardDesign,
    matchInfo,
}) {
    let refSection;

    if (standardDesign?.components?.length) {
        const sourceLabel =
            matchInfo?.tier === 1 ? "STORED PRESET — industry standard design" :
                matchInfo?.tier === 2 ? "MONGODB CACHE — previously generated and stored" :
                    matchInfo?.tier === 3 ? "AI-GENERATED — just created and saved to DB for future users" :
                        "REFERENCE DESIGN";

        // ── Scale context string
        const scaleContext = standardDesign.estimatedScale
            ? Object.entries(standardDesign.estimatedScale)
                .map(([k, v]) => `${k}: ${v}`)
                .join(" | ")
            : null;

        // ── Top 2 key flows formatted
        const flowEntries = Object.entries(standardDesign.keyFlows || {}).slice(0, 2);
        const flowSection = flowEntries.length
            ? `Expected data flows (check if user's edges follow these paths):\n` +
            flowEntries.map(([name, steps]) =>
                `  [${name}]: ${steps.slice(0, 4).join(" → ")}`
            ).join("\n")
            : null;

        // ── Expected edges
        const edgesSection = standardDesign.expectedEdges?.length
            ? `Critical connections that MUST exist in the design:\n` +
            standardDesign.expectedEdges.slice(0, 12)
                .map((e) => `  • ${e}`)
                .join("\n") +
            `\nPenalise if key connections are missing or reversed.`
            : null;

        // ── Fault tolerance
        const faultSection = standardDesign.faultToleranceMechanisms?.length
            ? `Fault tolerance mechanisms to reward if present:\n` +
            standardDesign.faultToleranceMechanisms.slice(0, 3)
                .map((f) => `  • ${f}`)
                .join("\n")
            : null;

        refSection = `## REFERENCE DESIGN (${sourceLabel})

Summary: ${standardDesign.summary || ""}
${scaleContext ? `\nSystem scale context (judge if design handles this load): ${scaleContext}` : ""}

Expected components (in order):
${(standardDesign.components || []).slice(0, 14).map((c, i) => `  ${i + 1}. ${c}`).join("\n")}

Critical must-have components: ${(standardDesign.criticalComponents || []).join(", ")}
${edgesSection ? `\n${edgesSection}` : ""}
${flowSection ? `\n${flowSection}` : ""}
${faultSection ? `\n${faultSection}` : ""}

Anti-patterns to detect and penalise:
${(standardDesign.antiPatterns || []).slice(0, 5).map((a) => `  • ${a}`).join("\n")}

Scalability decisions to reward if present:
${(standardDesign.scalabilityDecisions || []).slice(0, 4).map((d) => `  • ${d}`).join("\n")}

EVALUATION INSTRUCTIONS:
1. Compare user's components against the expected components list.
2. Check user's edges against expectedEdges — missing critical connections = lower completeness score.
3. Check if any edges are WRONG DIRECTION (e.g. DB → Client directly) — flag as anti-pattern.
4. Penalise every missing critical component harshly.
5. Detect anti-patterns found in the user's design and call them out.
6. Reward scalability and fault-tolerance decisions that align with the reference.
7. Consider the system scale — is this design capable of handling the stated load?`;

    } else {
        // No reference found and AI generation failed — evaluate on general principles
        refSection = `## NO REFERENCE AVAILABLE
No stored or AI-generated reference was found for "${problemTitle}".
Evaluate based on general distributed systems principles.
Use your knowledge of similar systems to judge what components are expected.`;
    }

    return `You are a principal software engineer at FAANG conducting a system design interview.

${refSection}

## USER'S SUBMITTED DESIGN
Problem: "${problemTitle}"
Components placed on diagram: ${nodeList}
Connections drawn: ${edgeList || "none specified"}
User's written explanation: ${textExplanation || "none provided"}

## SCORING RUBRIC (1–10)
9–10  Hire immediately. Near-identical to industry standard with strong reasoning.
7–8   Strong candidate. Core components correct, minor gaps.
5–6   Average. Basics present but missing key scalability or reliability components.
3–4   Below average. Major architectural gaps or anti-patterns present.
1–2   Not ready. Fundamental distributed systems misunderstandings.

Be DIRECT and HONEST. Real interviewers do not give inflated scores.

Return ONLY valid JSON. No markdown. No text before or after the JSON. Keep values concise.

{
  "score": <float 1.0-10.0>,
  "summary": "<2-3 sentence honest interviewer assessment>",
  "strengths": ["<specific strength>", "<specific strength>", "<specific strength>"],
  "improvements": ["<actionable improvement>", "<improvement>", "<improvement>"],
  "weakAreas": ["<weak area category>", "<weak area category>"],
  "referenceComponents": ["<c1>", "<c2>", "<c3>", "<c4>", "<c5>", "<c6>"],
  "missingCriticalComponents": ["<missing component if any>"],
  "antiPatternsFound": ["<anti-pattern found in user design if any>"],
  "wrongConnections": ["<edge that is wrong or missing e.g. Client → DB directly>"],
  "scoringBreakdown": {
    "scalability": <1-10>,
    "reliability": <1-10>,
    "completeness": <1-10>,
    "dataModeling": <1-10>,
    "communicationClarity": <1-10>
  },
  "comparisonWithStandard": {
    "matchedComponents": ["<component user got right>"],
    "missingFromUser": ["<standard component not in user design>"],
    "userHadExtra": ["<user component not in standard but valid>"],
    "correctEdges": ["<connection the user drew correctly>"],
    "wrongOrMissingEdges": ["<critical connection missing or reversed>"],
    "verdict": "<one sentence: how close to the reference standard>"
  }
}`;
}

// GET /api/designs/history
exports.getHistory = async (req, res) => {
    try {
        const attempts = await Attempt.find({ user: req.user._id, status: "evaluated" })
            .sort({ createdAt: -1 })
            .limit(50)
            .select("-diagramData");
        res.json({ attempts });
    } catch {
        console.error("getHistory", err);
        res.status(500).json({ error: "Failed to load history." });
    }
};

// GET /api/designs/:id
exports.getAttempt = async (req, res) => {
    try {
        const attempt = await Attempt.findOne({ _id: req.params.id, user: req.user._id });
        if (!attempt) return res.status(404).json({ error: "Attempt not found." });
        res.json({ attempt });
    } catch {
        res.status(500).json({ error: "Failed to load attempt." });
    }
};