import yt from "../assets/youtube.png";
import ur from "../assets/url.png";
import ig from "../assets/instagram.png";
import wa from "../assets/whatsapp.png";
import sw from "../assets/stopwatch.png";
import x from "../assets/twitter.png";
import nf from "../assets/netflix.png";
import git from "../assets/github.png";
import gd from "../assets/google-drive.png";
import db from "../assets/dropbox.png";
import ub from "../assets/uber.png";
import ch from "../assets/chat.png";
import am from "../assets/amazon.png";
import bell from "../assets/bell.png";

export const DEFAULT_PROBLEMS = [
    { slug: "url-shortener", title: "Design a URL Shortener", difficulty: "Easy", tags: ["Hashing", "Redirect", "Cache", "Analytics"], time: "30", icon: <img src={ur} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#0EA5E9" },
    { slug: "twitter", title: "Design a Twitter/X", difficulty: "Hard", tags: ["Feed", "Social Graph", "Search", "Trending"], time: "60", icon: <img src={x} alt="youtube" style={{ width:40, height:40, objectFit: 'contain' }} />, color: "#000000" },
    { slug: "chat", title: "Design a real-time chat app", difficulty: "Medium", tags: ["WebSocket", "Messaging", "Queue", "Push"], time: "45", icon: <img src={ch} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#6366F1" },
    { slug: "netflix", title: "Design a Netflix", difficulty: "Hard", tags: ["CDN", "Encoding", "Streaming", "Recommendation"], time: "60", icon: <img src={nf} alt="youtube" style={{ width:40, height:40, objectFit: 'contain' }} />, color: "#E50914" },
    { slug: "rate-limiter", title: "Design a rate limiter", difficulty: "Medium", tags: ["Redis", "Algorithm", "API Gateway", "Distributed"], time: "30", icon: <img src={sw} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#8B5CF6" },
    { slug: "google-drive", title: "Design a Google Drive", difficulty: "Medium", tags: ["Storage", "Sync", "Auth", "Metadata DB", "CDN"], time: "60", icon: <img src={gd} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#34A853" },
    { slug: "whatsapp", title: "Design a WhatsApp", difficulty: "Medium", tags: ["Message", "E2E", "Push Notification"], time: "60", icon: <img src={wa} alt="youtube" style={{ width: 34, height: 34, objectFit: 'contain' }} />, color: "#25D366" },
    { slug: "uber", title: "Design a Uber", difficulty: "Hard", tags: ["GPS", "Matching", "Real-Time", "Maps"], time: "45", icon: <img src={ub} alt="youtube" style={{ width:45, height:45, objectFit: 'contain' }} />, color: "#000000" },
    { slug: "youtube", title: "Design a Youtube", difficulty: "Medium", tags: ["CDN", "Streaming", "Storage", "Video"], time: "60", icon: <img src={yt} alt="youtube" style={{ width:24, height:24, objectFit: 'contain' }} />, color: "#FF0000" },
    { slug: "instagram", title: "Design a Instagram", difficulty: "Hard", tags: ["Feed", "CDN", "Stories", "Search", "Graph"], time: "60", icon: <img src={ig} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#E1306C" },
    { slug: "amazon", title: "Design a Amazon", difficulty: "Hard", tags: ["E-commerce", "Search", "Inventory", "Payment", "CDN"], time: "60", icon: <img src={am} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#FF9900" },
    { slug: "dropbox", title: "Design a Dropbox", difficulty: "Medium", tags: ["Storage", "Sync", "CDN", "Distributed Systems"], time: "60", icon: <img src={db} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#0061FF" },
    { slug: "notification-system", title: "Design a Notification System", difficulty: "Easy", tags: ["Queue", "Push", "Email", "SMS"], time: "25", icon: <img src={bell} alt="youtube" style={{ width:30, height:30, objectFit: 'contain' }} />, color: "#F59E0B" },
    { slug: "github", title: "Design a Github", difficulty: "Hard", tags: ["Distributed Systems", "Storage", "Collaboration"], time: "60", icon: <img src={git} alt="youtube" style={{ width:40, height:40, objectFit: 'contain' }} />, color: "#0061FF" },
];

export const DIAGRAM_COMPONENTS = [
    { type: "API Gateway", emoji: "🌐" },
    { type: "Admin Dashboard", emoji: "🛠" },
    { type: "Analytics DB", emoji: "📊" },
    { type: "Analytics Pipeline", emoji: "🔄" },
    { type: "Analytics Service", emoji: "📈" },
    { type: "Asset Management Service", emoji: "📦" },
    { type: "Auth Service", emoji: "🔐" },
    { type: "Billing", emoji: "💳" },
    { type: "Block Download Service", emoji: "⛔" },
    { type: "Block Upload Service", emoji: "🚫" },
    { type: "Bloom Filter", emoji: "🌸" },
    { type: "CDN", emoji: "🌍" },
    { type: "CI/CD Service", emoji: "🚀" },
    { type: "Cache", emoji: "⚡" },
    { type: "Channel Service", emoji: "📡" },
    { type: "Chaos Engineering", emoji: "💥" },
    { type: "Client", emoji: "💻" },
    { type: "Code Review Service", emoji: "👀" },
    { type: "Comment & Like Service", emoji: "💬" },
    { type: "Comment & Reaction Service", emoji: "😀" },
    { type: "Content Catalog Service", emoji: "📚" },
    { type: "Deduplication Service", emoji: "♻" },
    { type: "Delivery Tracker Service", emoji: "🚚" },
    { type: "Distributed Cache", emoji: "🗂" },
    { type: "Download Service", emoji: "⬇" },
    { type: "Driver App", emoji: "🚗" },
    { type: "Email Service", emoji: "📧" },
    { type: "Encoding Pipeline", emoji: "🎞" },
    { type: "Event Ingestion Service", emoji: "📥" },
    { type: "Feed Service", emoji: "📰" },
    { type: "Fixed Window Algo Worker", emoji: "⏱" },
    { type: "Gateway Service", emoji: "🔌" },
    { type: "Geospatial DB", emoji: "🗺" },
    { type: "Git Service", emoji: "🌿" },
    { type: "Graph DB", emoji: "🕸" },
    { type: "Group Service", emoji: "👥" },
    { type: "Guild Service", emoji: "🏰" },
    { type: "In-App Notification Service", emoji: "🔔" },
    { type: "Issue Tracker Service", emoji: "🐞" },
    { type: "Key Management Service", emoji: "🗝" },
    { type: "Leaky Bucket Algo Worker", emoji: "🪣" },
    { type: "Load Balancer", emoji: "⚖" },
    { type: "Location Service", emoji: "📍" },
    { type: "Maps", emoji: "🗺" },
    { type: "Matching Service", emoji: "🤝" },
    { type: "Media Service", emoji: "🎬" },
    { type: "Media Upload Service", emoji: "🎥" },
    { type: "Message Queue", emoji: "📬" },
    { type: "Message Service", emoji: "✉" },
    { type: "Message Store", emoji: "🗄" },
    { type: "Metadata DB", emoji: "🧾" },
    { type: "Metadata Service", emoji: "📋" },
    { type: "Monitoring", emoji: "📡" },
    { type: "NoSQL DB", emoji: "🧩" },
    { type: "Notification API Service", emoji: "🔗" },
    { type: "Notification Router", emoji: "➡" },
    { type: "Notification Service", emoji: "🔔" },
    { type: "Object Storage", emoji: "🪣" },
    { type: "Pages Service", emoji: "📄" },
    { type: "Payment Service", emoji: "💰" },
    { type: "Post Service", emoji: "📝" },
    { type: "Presence Service", emoji: "🟢" },
    { type: "Preview Service", emoji: "👁" },
    { type: "Pricing Service", emoji: "💲" },
    { type: "Push Notification Service", emoji: "📲" },
    { type: "Rate Limiter", emoji: "🚦" },
    { type: "Rate Limiter Service", emoji: "🚧" },
    { type: "Recommendation Service", emoji: "🤖" },
    { type: "Redirect Service", emoji: "🔀" },
    { type: "Relational DB", emoji: "🗃" },
    { type: "Repository Storage", emoji: "📁" },
    { type: "Retry Service", emoji: "🔁" },
    { type: "Rule Service", emoji: "📏" },
    { type: "SMS Service", emoji: "📩" },
    { type: "Search Service", emoji: "🔍" },
    { type: "Sharing Service", emoji: "🔗" },
    { type: "Shortening Service", emoji: "✂" },
    { type: "Sliding Window Algo Worker", emoji: "🪟" },
    { type: "Story Service", emoji: "📖" },
    { type: "Streaming Service", emoji: "📺" },
    { type: "Sync Engine", emoji: "⚙" },
    { type: "Sync Service", emoji: "🔄" },
    { type: "Template Service", emoji: "🧩" },
    { type: "Thumbnail Service", emoji: "🖼" },
    { type: "Timeline Service", emoji: "⏳" },
    { type: "Token Bucket Algo Worker", emoji: "🎟" },
    { type: "Transcoding Service", emoji: "🎬" },
    { type: "Trending", emoji: "🔥" },
    { type: "Trip Management Service", emoji: "🧳" },
    { type: "Tweet Service", emoji: "🐦" },
    { type: "Upload Service", emoji: "⬆" },
    { type: "User Service", emoji: "👤" },
    { type: "User DB", emoji: "🗃" },
    { type: "User Preference Service", emoji: "⚙" },
    { type: "User Profile Service", emoji: "📄" },
    { type: "Viewing History DB", emoji: "📜" },
    { type: "Voice / Video Service (WebRTC SFU)", emoji: "🎙" },
    { type: "WebSocket Gateway", emoji: "🔌" },
    { type: "Webhook Service", emoji: "🪝" },
];

export const NODE_STYLES = {
    "Client": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#3B82F6", color: "#1D4ED8" },
    "Driver App": { bg: "#F0FDF4", darkBg: "#052e16", border: "#22C55E", color: "#15803D" },
    "Admin Dashboard": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#64748B", color: "#5D6D83" },
    "API Gateway": { bg: "#FFF7ED", darkBg: "#7c2d12", border: "#F97316", color: "#C2410C" },
    "Gateway Service": { bg: "#FFF7ED", darkBg: "#6b2110", border: "#FB923C", color: "#C2410C" },
    "Load Balancer": { bg: "#F0FDF4", darkBg: "#14532d", border: "#22C55E", color: "#15803D" },
    "WebSocket Gateway": { bg: "#F0FDF4", darkBg: "#064e3b", border: "#34D399", color: "#059669" },
    "Rate Limiter": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#F87171", color: "#B91C1C" },
    "Rate Limiter Service": { bg: "#FFF1F2", darkBg: "#3f0808", border: "#F43F5E", color: "#BE123C" },
    "Auth Service": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#64748B", color: "#5D6D83" },
    "Key Management Service": { bg: "#FFFBEB", darkBg: "#3b1f02", border: "#F59E0B", color: "#92400E" },
    "Cache": { bg: "#FFFBEB", darkBg: "#422006", border: "#EAB308", color: "#A16207" },
    "Distributed Cache": { bg: "#FEFCE8", darkBg: "#3b2906", border: "#FACC15", color: "#854D0E" },
    "Relational DB": { bg: "#FFF1F2", darkBg: "#4c0519", border: "#F43F5E", color: "#BE123C" },
    "NoSQL DB": { bg: "#FDF4FF", darkBg: "#2e1065", border: "#A855F7", color: "#7E22CE" },
    "Graph DB": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#818CF8", color: "#4338CA" },
    "Geospatial DB": { bg: "#F0FDF4", darkBg: "#052e16", border: "#4ADE80", color: "#166534" },
    "Analytics DB": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#60A5FA", color: "#1D4ED8" },
    "Metadata DB": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#94A3B8", color: "#475569" },
    "User DB": { bg: "#EFF6FF", darkBg: "#172554", border: "#3B82F6", color: "#1D4ED8" },
    "Message Store": { bg: "#ECFEFF", darkBg: "#083344", border: "#06B6D4", color: "#0E7490" },
    "Viewing History DB": { bg: "#FFF7ED", darkBg: "#431407", border: "#FB923C", color: "#C2410C" },
    "Repository Storage": { bg: "#F1F5F9", darkBg: "#1e293b", border: "#94A3B8", color: "#475569" },
    "Object Storage": { bg: "#F0FDF4", darkBg: "#052e16", border: "#4ADE80", color: "#166534" },
    "Message Queue": { bg: "#ECFEFF", darkBg: "#083344", border: "#06B6D4", color: "#0E7490" },
    "CDN": { bg: "#FDF4FF", darkBg: "#4a044e", border: "#D946EF", color: "#A21CAF" },
    "Streaming Service": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#FB7185", color: "#BE123C" },
    "Encoding Pipeline": { bg: "#FFF7ED", darkBg: "#431407", border: "#F97316", color: "#C2410C" },
    "Transcoding Service": { bg: "#FFF7ED", darkBg: "#7c2d12", border: "#FB923C", color: "#C2410C" },
    "User Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#3B82F6", color: "#1D4ED8" },
    "User Profile Service": { bg: "#EFF6FF", darkBg: "#172554", border: "#60A5FA", color: "#1E40AF" },
    "User Preference Service": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#818CF8", color: "#4338CA" },
    "Feed Service": { bg: "#F0FDF4", darkBg: "#052e16", border: "#86EFAC", color: "#166534" },
    "Post Service": { bg: "#F0FDF4", darkBg: "#14532d", border: "#4ADE80", color: "#15803D" },
    "Tweet Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#38BDF8", color: "#0369A1" },
    "Story Service": { bg: "#FDF4FF", darkBg: "#3b0764", border: "#C084FC", color: "#7E22CE" },
    "Timeline Service": { bg: "#FEFCE8", darkBg: "#422006", border: "#FACC15", color: "#854D0E" },
    "Comment & Like Service": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#FDA4AF", color: "#BE123C" },
    "Comment & Reaction Service": { bg: "#FFF7ED", darkBg: "#7c2d12", border: "#FCA5A1", color: "#C2410C" },
    "Trending": { bg: "#FFF7ED", darkBg: "#431407", border: "#F97316", color: "#C2410C" },
    "Media Service": { bg: "#1a1a1a", darkBg: "#111111", border: "#E50914", color: "#E50914" },
    "Media Upload Service": { bg: "#FFF1F2", darkBg: "#4c0519", border: "#FB7185", color: "#BE123C" },
    "Content Catalog Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#7DD3FC", color: "#0369A1" },
    "Thumbnail Service": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#CBD5E1", color: "#475569" },
    "Preview Service": { bg: "#F8FAFC", darkBg: "#0f172a", border: "#94A3B8", color: "#5D6D83" },
    "Recommendation Service": { bg: "#FAF5FF", darkBg: "#3b0764", border: "#A855F7", color: "#7E22CE" },
    "Search Service": { bg: "#FFF7ED", darkBg: "#431407", border: "#FB923C", color: "#C2410C" },
    "Notification Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#60A5FA", color: "#1D4ED8" },
    "Notification API Service": { bg: "#EFF6FF", darkBg: "#172554", border: "#3B82F6", color: "#1D4ED8" },
    "Notification Router": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#818CF8", color: "#4338CA" },
    "In-App Notification Service": { bg: "#EEF2FF", darkBg: "#2e1065", border: "#A78BFA", color: "#6D28D9" },
    "Push Notification Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#7DD3FC", color: "#0369A1" },
    "Email Service": { bg: "#F0FDF4", darkBg: "#052e16", border: "#4ADE80", color: "#166534" },
    "SMS Service": { bg: "#F0FDF4", darkBg: "#14532d", border: "#86EFAC", color: "#15803D" },
    "Message Service": { bg: "#ECFEFF", darkBg: "#083344", border: "#06B6D4", color: "#0E7490" },
    "Channel Service": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#6366F1", color: "#4338CA" },
    "Group Service": { bg: "#EEF2FF", darkBg: "#2e1065", border: "#818CF8", color: "#4338CA" },
    "Guild Service": { bg: "#FAF5FF", darkBg: "#3b0764", border: "#C084FC", color: "#7E22CE" },
    "Presence Service": { bg: "#F0FDF4", darkBg: "#064e3b", border: "#34D399", color: "#059669" },
    "Location Service": { bg: "#F0FDF4", darkBg: "#052e16", border: "#22C55E", color: "#15803D" },
    "Maps": { bg: "#F0FDF4", darkBg: "#14532d", border: "#4ADE80", color: "#166534" },
    "Matching Service": { bg: "#FFF7ED", darkBg: "#431407", border: "#F97316", color: "#C2410C" },
    "Trip Management Service": { bg: "#FFF7ED", darkBg: "#7c2d12", border: "#FB923C", color: "#C2410C" },
    "Delivery Tracker Service": { bg: "#FFFBEB", darkBg: "#422006", border: "#FCD34D", color: "#92400E" },
    "Sync Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#38BDF8", color: "#0369A1" },
    "Sync Engine": { bg: "#EFF6FF", darkBg: "#172554", border: "#60A5FA", color: "#1E40AF" },
    "Upload Service": { bg: "#F0FDF4", darkBg: "#14532d", border: "#4ADE80", color: "#15803D" },
    "Download Service": { bg: "#F0FDF4", darkBg: "#052e16", border: "#86EFAC", color: "#166534" },
    "Block Upload Service": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#F87171", color: "#B91C1C" },
    "Block Download Service": { bg: "#FFF1F2", darkBg: "#3f0808", border: "#FCA5A1", color: "#BE123C" },
    "Sharing Service": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#818CF8", color: "#4338CA" },
    "Asset Management Service": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#94A3B8", color: "#475569" },
    "Payment Service": { bg: "#F0FDF4", darkBg: "#052e16", border: "#22C55E", color: "#15803D" },
    "Billing": { bg: "#F0FDF4", darkBg: "#14532d", border: "#4ADE80", color: "#166534" },
    "Pricing Service": { bg: "#FFFBEB", darkBg: "#422006", border: "#EAB308", color: "#A16207" },
    "Analytics Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#60A5FA", color: "#1D4ED8" },
    "Analytics Pipeline": { bg: "#EFF6FF", darkBg: "#172554", border: "#3B82F6", color: "#1E40AF" },
    "Monitoring": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#60A5FA", color: "#1D4ED8" },
    "Event Ingestion Service": { bg: "#ECFEFF", darkBg: "#083344", border: "#22D3EE", color: "#0891B2" },
    "Shortening Service": { bg: "#FDF4FF", darkBg: "#4a044e", border: "#D946EF", color: "#A21CAF" },
    "Redirect Service": { bg: "#FAF5FF", darkBg: "#3b0764", border: "#C084FC", color: "#7E22CE" },
    "Fixed Window Algo Worker": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#F87171", color: "#B91C1C" },
    "Sliding Window Algo Worker": { bg: "#FFF1F2", darkBg: "#3f0808", border: "#F43F5E", color: "#BE123C" },
    "Token Bucket Algo Worker": { bg: "#FFFBEB", darkBg: "#422006", border: "#EAB308", color: "#A16207" },
    "Leaky Bucket Algo Worker": { bg: "#FFFBEB", darkBg: "#3b1f02", border: "#F59E0B", color: "#92400E" },
    "CI/CD Service": { bg: "#F8FAFC", darkBg: "#0f172a", border: "#64748B", color: "#5D6D83" },
    "Code Review Service": { bg: "#F1F5F9", darkBg: "#1e293b", border: "#94A3B8", color: "#475569" },
    "Git Service": { bg: "#F8FAFC", darkBg: "#14532d", border: "#4ADE80", color: "#166534" },
    "Issue Tracker Service": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#F87171", color: "#B91C1C" },
    "Pages Service": { bg: "#EFF6FF", darkBg: "#1e3a5f", border: "#60A5FA", color: "#1D4ED8" },
    "Metadata Service": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#94A3B8", color: "#475569" },
    "Deduplication Service": { bg: "#ECFEFF", darkBg: "#083344", border: "#06B6D4", color: "#0E7490" },
    "Bloom Filter": { bg: "#FDF4FF", darkBg: "#4a044e", border: "#E879F9", color: "#A21CAF" },
    "Retry Service": { bg: "#FFF7ED", darkBg: "#431407", border: "#FB923C", color: "#C2410C" },
    "Rule Service": { bg: "#F8FAFC", darkBg: "#1e293b", border: "#64748B", color: "#5D6D83" },
    "Template Service": { bg: "#EEF2FF", darkBg: "#1e1b4b", border: "#A5B4FC", color: "#4338CA" },
    "Webhook Service": { bg: "#FAF5FF", darkBg: "#3b0764", border: "#C084FC", color: "#7E22CE" },
    "Chaos Engineering": { bg: "#FFF1F2", darkBg: "#450a0a", border: "#F87171", color: "#B91C1C" },
    "Voice / Video Service": { bg: "#F0FDF4", darkBg: "#064e3b", border: "#34D399", color: "#059669" },
    "Microservice": { bg: "#FAF5FF", darkBg: "#3b0764", border: "#A855F7", color: "#7E22CE" },
};

export const getNodeStyle = (type, theme) => {
    const s = NODE_STYLES[type] || NODE_STYLES["Microservice"];
    return { bg: theme === "dark" ? s.darkBg : s.bg, border: s.border, color: s.color };
};